from datetime import datetime
from decimal import Decimal

from fastapi import HTTPException
from sqlalchemy.orm import Session, joinedload

from app.models.models import Account, Transaction, User


def get_transaction_for_user(db: Session, reference: str, user: User) -> Transaction:
    if not user.account:
        raise HTTPException(status_code=400, detail="Account not found")

    txn = (
        db.query(Transaction)
        .options(
            joinedload(Transaction.sender).joinedload(Account.user),
            joinedload(Transaction.receiver).joinedload(Account.user),
        )
        .filter(Transaction.reference == reference)
        .first()
    )
    if not txn:
        raise HTTPException(status_code=404, detail="Transaction not found")

    account_id = user.account.id
    if txn.sender_account_id != account_id and txn.receiver_account_id != account_id:
        raise HTTPException(status_code=403, detail="Access denied")

    return txn


def _format_amount(amount: Decimal) -> str:
    return f"₦{float(amount):,.2f}"


def _format_datetime(dt: datetime) -> str:
    return dt.strftime("%d %B %Y at %H:%M UTC")


def build_receipt_html(txn: Transaction, viewer_account_id: str) -> str:
    is_debit = txn.sender_account_id == viewer_account_id
    direction = "Debit (money sent)" if is_debit else "Credit (money received)"
    counterparty_account = txn.receiver if is_debit else txn.sender
    counterparty_user = counterparty_account.user if counterparty_account else None

    viewer_account = txn.sender if is_debit else txn.receiver
    viewer_user = viewer_account.user if viewer_account else None

    status = txn.status.value if hasattr(txn.status, "value") else str(txn.status)
    status_color = {
        "successful": "#166534",
        "pending": "#b45309",
        "failed": "#b91c1c",
        "reversed": "#525252",
    }.get(status, "#525252")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>SmartBank Receipt — {txn.reference}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, sans-serif; background: #fafafa; color: #171717; margin: 0; padding: 32px 16px; }}
    .receipt {{ max-width: 520px; margin: 0 auto; background: #fff; border: 1px solid #e5e5e5; border-radius: 16px; overflow: hidden; }}
    .header {{ background: #0a0a0a; color: #fff; padding: 24px 28px; }}
    .header h1 {{ margin: 0; font-size: 1.25rem; letter-spacing: 0.05em; }}
    .header p {{ margin: 6px 0 0; font-size: 0.75rem; color: #a3a3a3; text-transform: uppercase; letter-spacing: 0.1em; }}
    .body {{ padding: 28px; }}
    .amount {{ font-size: 2rem; font-weight: 700; margin: 0 0 4px; }}
    .direction {{ font-size: 0.8rem; color: #737373; margin-bottom: 24px; }}
    .status {{ display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #fff; background: {status_color}; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
    td {{ padding: 10px 0; border-bottom: 1px solid #f5f5f5; vertical-align: top; }}
    td.label {{ color: #737373; width: 42%; }}
    td.value {{ font-weight: 500; text-align: right; word-break: break-word; }}
    .footer {{ padding: 20px 28px; background: #fafafa; font-size: 0.7rem; color: #a3a3a3; line-height: 1.5; border-top: 1px solid #f5f5f5; }}
    @media print {{ body {{ background: #fff; padding: 0; }} .receipt {{ border: none; box-shadow: none; }} }}
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <h1>SmartBank</h1>
      <p>Transaction receipt</p>
    </div>
    <div class="body">
      <p class="amount">{_format_amount(txn.amount)}</p>
      <p class="direction">{direction}</p>
      <p style="margin-bottom: 20px;"><span class="status">{status}</span></p>
      <table>
        <tr><td class="label">Reference</td><td class="value">{txn.reference}</td></tr>
        <tr><td class="label">Date</td><td class="value">{_format_datetime(txn.created_at)}</td></tr>
        <tr><td class="label">Narration</td><td class="value">{txn.narration or "Transfer"}</td></tr>
        <tr><td class="label">Your account</td><td class="value">{viewer_account.account_number if viewer_account else "—"}</td></tr>
        <tr><td class="label">Your name</td><td class="value">{viewer_user.full_name if viewer_user else "—"}</td></tr>
        <tr><td class="label">Counterparty</td><td class="value">{counterparty_user.full_name if counterparty_user else "—"}</td></tr>
        <tr><td class="label">Counterparty account</td><td class="value">{counterparty_account.account_number if counterparty_account else "—"}</td></tr>
      </table>
    </div>
    <div class="footer">
      This receipt was generated by SmartBank. Keep it for your records.
      For support, quote reference <strong>{txn.reference}</strong>.
    </div>
  </div>
</body>
</html>"""
