"""create all tables

Revision ID: a20e1322a627
Revises: 
Create Date: 2026-05-19 22:06:35.054436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20e1322a627'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_registry',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nin', sa.String(length=11), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_registry_nin'), 'identity_registry', ['nin'], unique=True)
    op.create_table('otp_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=30), server_default='registration', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_contact_value'), 'otp_records', ['contact_value'], unique=False)
    op.create_index(op.f('ix_otp_records_purpose'), 'otp_records', ['purpose'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('kyc_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='kyctier'), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'FROZEN', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('nin_verified', sa.Boolean(), nullable=False),
    sa.Column('transfer_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ledger_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('sender_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('receiver_account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('TRANSFER', 'REVERSAL', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transaction_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_account_txn', 'ledger_entries', ['account_id', 'transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_account_txn', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_audit_user_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_records_purpose'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_contact_value'), table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_index(op.f('ix_identity_registry_nin'), table_name='identity_registry')
    op.drop_table('identity_registry')
    # ### end Alembic commands ###
